#
# Run config for debugging.
#
model:
  load_path:
    value: null
data:
  data_dir:
    #value: /mnt/nas05/astrodata01/astroml_data/sdomlv2_full/sdomlv2.zarr
    value: /home/marius/data/sdomlv2_full/sdomlv2.zarr
  dataset:
    value: SDOMLDatasetV2
  num_data_loader_workers:
    value: 16
  prefetch_factor:
    value: 4
  batch_size:
    value: 32
  sdo_ml_v2:
    train_year:
      value:
        - "2012"
    train_start_date:
      value: null
    train_end_date:
      value: null
    test_year:
      value:
        - "2011"
    test_start_date:
      value: null
    test_end_date:
      value: null
    train_val_split_ratio:
      value: 0.9
    train_val_split_temporal_chunk_size:
      value: 14d
    sampling_strategy:
      value: "chunk"
    mask_limb:
      value: false
    reduce_memory:
      value: true
predict:
  mode:
    value: sample
  pred_dir:
    value: "./output/predictions"
log_dir:
  value: "./output/train-sdo-ml"
train:
  wandb_run_id:
    value: null
  n_epochs:
    value: 20
  early_stopping:
    value: true
  use_geco:
    value: false
  profile:
    value: true
  fast_dev_run:
    value: 100
devices:
  gpus:
    value:
      - 3
