model:
  load_path:
    value: null
data:
  data_dir:
    value: /mnt/nas05/astrodata01/astroml_data/sdomlv2.zarr
  dataset:
    value: SDOMLDatasetV2
  num_data_loader_workers:
    value: 16
  prefetch_factor:
    value: 8
  batch_size:
    value: 32
  sdo_ml_v2:
    train_year:
      value:
        - "2010"
        - "2011"
    train_start_date:
      value: null
    train_end_date:
      value: null
    train_year:
      value:
        - "2012"
    test_start_date:
      value: null
    test_end_date:
      value: null
    train_val_split_ratio:
      value: 0.8
    train_val_split_temporal_chunk_size:
      value: 3d
predict:
  mode:
    value: sample
  pred_dir:
    value: "./output/predictions"
log_dir:
  value: "./output/train-sdo-ml"
