model:
  load_path:
    value: /home/marius/sdo-cli/artifacts/model-kselxcp3:v3/model.ckpt
data:
  data_dir:
    value: /mnt/nas05/astrodata01/astroml_data/sdomlv2_full/sdomlv2.zarr
  dataset:
    value: SDOMLDatasetV2
  num_data_loader_workers:
    value: 16
  prefetch_factor:
    value: 4
  batch_size:
    value: 32
  sdo_ml_v2:
    train_year:
      value:
        - "2010"
        - "2012"
        - "2013"
        - "2015"
        - "2017"
        - "2018"
        - "2020"
    train_start_date:
      value: null
    train_end_date:
      value: null
    test_year:
      value:
        - "2011"
        - "2014"
        - "2016"
        - "2019"
    test_start_date:
      value: null
    test_end_date:
      value: null
    train_val_split_ratio:
      value: 0.9
    train_val_split_temporal_chunk_size:
      value: 14d
    sampling_strategy:
      value: "chunk"
predict:
  mode:
    value: sample
  pred_dir:
    value: "./output/predictions"
log_dir:
  value: "./output/train-sdo-ml"
train:
  lr:
    value: 0.00001
  n_epochs:
    value: 20
  early_stopping:
    value: true
  use_geco:
    value: false
devices:
  gpus:
    value:
      - 2
