#
# Predict config for a threshold-based baseline model.
#
data:
  data_dir:
    value: /mnt/nas05/astrodata01/astroml_data/sdomlv2_full/sdomlv2.zarr
    #value: /home/marius/data/sdomlv2_full/sdomlv2.zarr
  dataset:
    value: SDOMLDatasetV2
  num_data_loader_workers:
    value: 8
  prefetch_factor:
    value: 4
  batch_size:
    value: 32
  sdo_ml_v2:
    train_year:
      value:
        - "2010"
        - "2012"
        - "2013"
        - "2015"
        - "2017"
        - "2018"
        - "2020"
    test_year:
      value:
        - "2011"
        - "2014"
        - "2016"
        - "2019"
    test_start_date:
      value: null
    test_end_date:
      value: null
    sampling_strategy:
      value: "chunk"
predict:
  mode:
    value: sample
  pred_dir:
    value: "./output/threshold/predictions"
log_dir:
  value: "./output/train-sdo-ml"
